### ISSUE TITLE
Bug Report: Unexpected value 'GooglePlaceModule' error on import

### ISSUE THREAD

**Issue by AhmedBoustani** [skynet2/ngx-google-places-autocomplete#1]
## Error Statement
ERROR in : Unexpected value 'GooglePlaceModule in [dir]/node_modules/ngx-google-places-autocomplete/ngx-google-places-autocomplete.module.d.ts' imported by the module 'AppModule in [dir]/src/app/app.module.ts'. Please add a [at]NgModule annotation.

## Steps to Reproduce
1. Install dependency
2. import module in app.module.ts and add it to imports array
3. run with `ng serve --aot`

## Environment
ngx-google-places-autocomplete: 1.0.0
cli: 1.6.3
angular: 5.1.3

node: 9.2.1
npm: 5.6.0

**Comment by skynet2** [comment]
Hi @AhmedBoustani ,

Please try the latest version 1.0.4 . It should work properly with angular-cli + aot.

**Comment by AhmedBoustani** [comment]
it works! thank you!!
