### ISSUE TITLE
Cannot Restrict Countries

### ISSUE THREAD

**Issue by Cassidie** [skynet2/ngx-google-places-autocomplete#117]
I am unable to restrict by countries. My code follows the property options object, setting the componentRestrictions to 'us', however I still get many countries in my results. Do I need to use the bounds information along with this restriction in order for it to work? Here's my code:

```
 public readonly addressAutocompleteOptions = new Options({
    componentRestrictions: { country: 'us' },
    fields: ['address_components'],
    types: ['address'],
  });
```

I've tried changing the country code value to different countries and I see no change in the UI.
Any ideas? I've looked through all the documentation I could fine, and it seems like this should just work with the componentRestrictions option set. :(

**Update**: I should note that I am using 
Angular v14.1.1 
ngx-google-places-autocomplete v2.0.5
typescript v4.7.2

**Comment by derciesto** [comment]
hi 
facing the same issue for a temporary solution is making parameter to optional
file path **node_modules\ngx-google-places-autocomplete\objects\options\options.d.ts**
`import { LatLng } from '../latLng';`
`import { LatLngBounds } from "../latLngBounds";`
`import { ComponentRestrictions } from "./componentRestrictions";`
`export declare class Options {`
    `bounds?: LatLngBounds;`
    `componentRestrictions: ComponentRestrictions;`
    `types: string[];`
    `fields: string[];`
    `strictBounds: boolean;`
    `origin?: LatLng;`
    `constructor(opt?: Partial<Options>);`
`}` 


its works for me

**Comment by Cassidie** [comment]
@derciesto Thank you for the information! However, I'm not understanding what you mean, or how it fixes the problem. Could you elaborate? What parameter are you referring to that would help restrict countries by becoming optional?

**Comment by Cassidie** [comment]
For anyone that was also having trouble with this, what I was doing was trying to set the options on the HTML input element as so:
`<input type="text" [attr.options]="autocompleteOptions">`

That does NOT work. I found an example in the repo that shows you can manually set the places options using ViewChild in ngAfterViewInit. This worked for me, successfully isolated the country.

```
In template:
 <input type="text" ngx-google-places-autocomplete #places="ngx-places" (onAddressChange)="onChange($event)" />

In Component:
 @ViewChild('places') public placesDirective!: GooglePlaceDirective;

  public ngAfterViewInit() {
    this.placesDirective.options.types = ['address'];
    this.placesDirective.options.componentRestrictions = { country: 'us' };
  }
```

 Hope this helps someone else!
