### ISSUE TITLE
Text box is disabled

### ISSUE THREAD

**Issue by KaranPato** [skynet2/ngx-google-places-autocomplete#12]
Whenever I click on the textbox, placeholder changes to oops! Something went wrong.
And even I don't have to click on that textbox after the page is reloaded, within 5-6 seconds it get's disabled

**Comment by skynet2** [comment]
Hi @KaranPato ,

Please check developer console for more details. 
The problem is in google library itself, probably you are using the wrong api key.

Thanks,
Stas

**Comment by KaranPato** [comment]
Actually, I was using the right API but from 16th July they have started a new rule to add the Billing details and all. That's why it isn't working. 

Anyways, Thanks
Karan
