### ISSUE TITLE
Duplicated drop down

### ISSUE THREAD

**Issue by ignaciolarranaga** [skynet2/ngx-google-places-autocomplete#13]
When you change the config the previous version stays there so you have multiple helpers at the same time.

Check this out:
<img width="610" alt="screen shot 2018-08-02 at 18 19 46" src="https://user-images.githubusercontent.com/15932965/43612018-565c049c-9681-11e8-933e-7b28346c5b3a.png">

**Comment by ignaciolarranaga** [comment]
I just created a PR with a possible solution #14 please take a look whenever possible and if possible release a version.

**Comment by skynet2** [comment]
Hi @ignaciolarranaga ,
Should be closed in 2.0.2.
(Sorry for long time without maintaining this repository) 

Thanks,
Stas
