### ISSUE TITLE
[options] object is not responsive to mutation

### ISSUE THREAD

**Issue by dwjohnston** [skynet2/ngx-google-places-autocomplete#16]
If I want to do a 'select your city in one input, and then select your address in a second input, I'd do it something like this'. 

```
    <input
      autocomplete="off"
      placeholder="City"
      name="city"
      ngx-google-places-autocomplete
      [options]="addressOptionsCity"
      #placesRef2="ngx-places"
      [value]="address.city"
      (change)="handleAddressTextChange($event)"
      (onAddressChange)="handleCityChange($event)"
    />
    <input
      autocomplete="street-address"
      placeholder="Property Address"
      name="address"
      ngx-google-places-autocomplete
      [options]="addressOptions"
      #placesRef="ngx-places"
      [(value)]="address.formatted_address"
      (change)="handleAddressTextChange($event)"
      (onAddressChange)="handleAddressChange($event)"
    />

```

```

  addressOptionsCity: Options = {
    bounds: null,
    componentRestrictions: {
      country: 'NZ'
    },
    types: ['(cities)']
  };
  addressOptions: Options = {
    bounds: null,
    componentRestrictions: {
      country: 'NZ'
    },
    types: ['address']
  };

  public handleCityChange(address: Address) {
    //this.addressOptions.location = address.geometry.location;  
    //this.addressOptions.radius = "150000"; //150km

    this.addressOptions.types = ['establishment']; //This is just to demonstrate that options isn't working. 

 }
```
~~**nb.** Options.location and Options.radius aren't in [your Options interface](https://github.com/skynet2/ngx-google-places-autocomplete/blob/master/src/objects/options/options.ts), but they are in the [Google Places API ](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest). My understanding is that they should still pass through.~~ I was looking at the wrong AutocompleteOptions object on the API. . [This is the correct one.](https://developers.google.com/maps/documentation/javascript/reference/places-widget#AutocompleteOptions). The question still remains though. 

In anycase - for this example - we'll just change the addressOptions type when the city changes. 
But in this example, the change the referenced options object does not propagate through to the autocompleter.

**Comment by dwjohnston** [comment]
Ok,  a hacky way to do this is to directly reference the `autocomplete` object, like this: 

```
export class AddressPickerComponent implements OnInit {

  @ViewChild('placesRef') placesRefAddress: GooglePlaceDirective;

  public handleCityChange(address: Address) {
    this.placesRefAddress.autocomplete.setTypes(['establishment']);
}
```

This will give you a typescript 'private member' warning, so a fix should be  create `getAutocomplete()` to expose the autocomplete object. 

The alternative is to add a lifecycle method on `ngOnChanges()` to reset the options object.

**Comment by cloudpbx-alex** [comment]
@dwjohnston 

Hi and thanks for a workaround!
Were you able to fix typescript warning without changing source code?

> This will give you a typescript 'private member' warning, so a fix should be create getAutocomplete() to expose the autocomplete object.

**Comment by skynet2** [comment]
Hi @dwjohnston ,

After changing options you should call reset function
https://github.com/skynet2/ngx-google-places-autocomplete/blob/master/src/ngx-google-places-autocomplete.directive.ts#L81
