### ISSUE TITLE
Not able to get photo_reference 

### ISSUE THREAD

**Issue by PKrupa94** [skynet2/ngx-google-places-autocomplete#18]
How user can able to get photo_reference in array of photo.without it user not able to display picture of place

**Comment by skynet2** [comment]
Hi @PKrupa94 ,

Use 2.0.3, here is an example of code 
        if(address.photos && address.photos.length > 0){
            console.dir(address.photos[0].getUrl({maxHeight:500,maxWidth:500}));
        }
