### ISSUE TITLE
Autocomplete after x characters

### ISSUE THREAD

**Issue by thari119** [skynet2/ngx-google-places-autocomplete#25]
anyway we can trigger the autocomplete after x number of characters to optimise the google api call outs?

**Comment by skynet2** [comment]
Hi @thari119 ,

There is a feature request on google for that https://issuetracker.google.com/issues/35823678

But looks like it`s closed as obsolete, because of new session-based billing for Places autocomplete. (last comment)

**Comment by dkruchok** [comment]
So maybe it's possible to control this with the library?
Something that can make it possible to prevent the request?
A simple example that doesn't work =)

                <input
                      matInput
                      placeholder="autocomplete"
                      formControlName="autocomplete"
                      (keyup)="onKey($event)"
                      ngx-google-places-autocomplete
                      #placesRef="ngx-places"
                      (onAddressChange)="handleAddressChange($event)"
                    />

```
  onKey(event: Event) {
    if (this.form.controls.autocomplete.value.length < 4) {
      // stop API request
      event.stopImmediatePropagation();
      event.preventDefault();
      event.stopPropagation();
    }
  }
```

**Comment by harleenarora** [comment]
any solution?
