### ISSUE TITLE
Google maps image from Address object

### ISSUE THREAD

**Issue by isaacpitwa** [skynet2/ngx-google-places-autocomplete#31]
how can i get the  google maps photo_reference from the address object

**Comment by skynet2** [comment]
Hi @isaacpitwa ,

According to docs, there is no photo_reference prop, there is a https://developers.google.com/maps/documentation/javascript/places#places_photos photo property, and it`s available under address https://github.com/skynet2/ngx-google-places-autocomplete/blob/master/src/objects/address.ts#L20
