### ISSUE TITLE
Script tag not accessible to Modals & Auxiliary Routes

### ISSUE THREAD

**Issue by byronglendon** [skynet2/ngx-google-places-autocomplete#32]
The only problem with this approach is that the google API <script> tag in index.html is not available to modals or named router-outlets? How do you give modals & named router-outlets access to the API key?
Is there a way to provide access the Google API key through a environment configuration setup rather?﻿

**Comment by JanMesaric** [comment]
I'm experiencing the same problem of not being to able to run it inside a modal, more specifically a ng-bootstrap modal.

**Comment by psenechal** [comment]
I just hit this problem this morning as well. It runs perfectly fine on a regular page. In a modal, I can see the network calls out to Google and the responses coming back, but the dropdown with the suggested addresses is not appearing.

**Comment by psenechal** [comment]
It ended up just being a styling issue in my case. My modals are set to z-index: 1050 and the default pac-container is set to z-index: 1000. I modified my global stylesheet with the following:

`.modal-open {
    .pac-container {
        z-index: 1050 !important;
    }
}`

The .modal-open class is applied to the body tag when an ng-modal is open.

**Comment by nektobit** [comment]
@psenechal thank you, this  CSS line save my day.
