### ISSUE TITLE
How to customize the fields?

### ISSUE THREAD

**Issue by ryakoviv** [skynet2/ngx-google-places-autocomplete#36]
How I can customize the fields like here https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete
![image](https://user-images.githubusercontent.com/11478971/55555400-e0c8ba80-56ed-11e9-9443-a3b103f3cb12.png)

**Comment by ryakoviv** [comment]
It is important because by customizing fields you can decrease number of request and save your money https://developers.google.com/places/web-service/usage-and-billing

**Comment by skynet2** [comment]
Hi @guillermogfer ,

Yes you are right, it can be done with options, current options class done have support for that fields, but as far as it`s javascript, you can add that field in options or cast object to any

cc @ryakoviv

**Comment by skynet2** [comment]
@ryakoviv new fields were added in 2.0.4
