### ISSUE TITLE
 Cannot find name 'GooglePlaceDirective'. angular 6

### ISSUE THREAD

**Issue by anuraggupta816** [skynet2/ngx-google-places-autocomplete#40]
I added google Directive but always following error occurs.  
 Cannot find name 'GooglePlaceDirective'.

**Comment by gagan95** [comment]
+1

**Comment by gagan95** [comment]
> I added google Directive but always following error occurs.
> Cannot find name 'GooglePlaceDirective'.

Hi @anuraggupta816  you can find the GooglePlaceDirective as below  :
 import { GooglePlaceDirective } from  "node_modules/ngx-google-places-autocomplete/ngx-google-places-autocomplete.directive";

this fixed my issue
