### ISSUE TITLE
Limiting Fields Returned

### ISSUE THREAD

**Issue by cicsolutions** [skynet2/ngx-google-places-autocomplete#41]
I'd like to limit the fields returned from the api call, as Google recommends limiting the returned results to avoid unnecessary data charges.

I see issue #36 is related to my question, and the recent commit to add fields to the options object.  However I'm not sure that is the correct setup, and when I add the following code to my options object, the handleAddressChange() method is no longer triggered: 

```
[options]="{ 
  types: ['(regions)'],
  fields: ['address_components']
}"
```

According to the documentation, the fields are not part of the options object, but are set via the setFields() method.
https://developers.google.com/maps/documentation/javascript/places-autocomplete#placeholder_text
(see: "For address forms, it is useful to get the address in structured format. To return the structured address for the selected place, call Autocomplete.setFields() and specify the address_components field.")

I think the way things are coded currently, having the fields property in the options object breaks the functionality of the directive.  I think we need to pass the fields in a different directive property or pull the fields from the existing options property and use the setFields() method to properly supply the desired fields in the api call.

Please let me know if I'm missing something or approaching this incorrectly.  And thank you so much for your work on this!

**Comment by MathieuMathurin** [comment]
@cicsolutions I had the same issue and I found out that the directive won't emit unless you include the 'place_id' field in the fields array.

Hope it helps :)

**Comment by swapnilmarathe007** [comment]
Hello Can some tell me where should i add options,
 i.e [options]="{ 
  types: ['(regions)'],
  fields: ['address_components']
}"
i have integrated in angular 2+ app.
Currently im calling handleAddressChange() function in my componet .

**Comment by swapnilmarathe007** [comment]
Yes i solved it, by adding "place_id" field in field array. Thanks!
