### ISSUE TITLE
onAddressChange should emit even if `place_id` is not included in the `fields` array

### ISSUE THREAD

**Issue by frabonomi** [skynet2/ngx-google-places-autocomplete#46]
Since it's possible to customize which data fields are returned by the API like this 

```javascript
options = {
  fields: ['address_components', 'geometry'],
}
```

shouldn't `onAddressChange` event emitter emit also if `place_id` is not included?
Right now it will only emit if `address.place_id` is defined ([see here](https://github.com/skynet2/ngx-google-places-autocomplete/blob/b433d8570bbf1a74c87fc3c46aecd6deabdb34bf/src/ngx-google-places-autocomplete.directive.ts#L95)).

**Comment by skynet2** [comment]
Fixed in 2.0.5
