### ISSUE TITLE
The Directive doesn't accept dynamic options

### ISSUE THREAD

**Issue by Andrii-A** [skynet2/ngx-google-places-autocomplete#48]
Hello,

I would like to use the directive with an options object and change some params based on user input in runtime. 

I found that the directives accepts options only once - when I change the options object, directive doesn't know about it.

Is it known issue?

thanks.

-------------------------------
HTML:

<input  type="text" matInput placeholder="Primary Address" formControlName="primaryAddressFormControl"
                   ngx-google-places-autocomplete
                   [options]="placesAutocompleteOptions" (onAddressChange)="handleAddressChange($event)"/>

-------------------------------
TS:

// onInit
    this.placesAutocompleteOptions =   {
        types: [ '(cities)' ],
        componentRestrictions: { country: 'us'}
      };

// when user selects new country in dropdown
  handleCountryChange($event) {   
    this.placesAutocompleteOptions.componentRestrictions.country = $event;
  }

**Comment by Mafandv** [comment]
https://github.com/skynet2/ngx-google-places-autocomplete/issues/33

https://github.com/skynet2/ngx-google-places-autocomplete/blob/master/example/app/app.component.ts#L51

**Comment by Andrii-A** [comment]
ref.reset() helped, thank you!

**Comment by KBeDevel** [comment]
This example should be documented/referenced in the [README](https://github.com/skynet2/ngx-google-places-autocomplete#options)
