### ISSUE TITLE
[bug report] Drop down result list does not stick to <input> on modal dialog

### ISSUE THREAD

**Issue by henryyue2010** [skynet2/ngx-google-places-autocomplete#49]
I use google place automcomplete on a modal dialog. If the screen is not scrolled, it works fine. but if the screen is scrolled, the dropdown list is not at the bottom of input, it could be anywhere and even not visible depends on how much the screen is scrolled. 

![image](https://user-images.githubusercontent.com/16337520/69923912-ff958000-150c-11ea-8016-8df527020323.png)

I use:
```
"ngx-google-places-autocomplete": "^2.0.4",
"@angular/common": "~7.2.0",
````
Is it a bug? If not, how to fix the issue? 
Thank you very much in advance for your help.

**Comment by shahzaibjaveed** [comment]
Still open this issue also facing the same troublesome. Please check and report as soon as possible.

**Comment by shafqatjan** [comment]
use this
.pac-container {
  z-index: 10000 !important;
}

**Comment by SeanGonzalezAbreu** [comment]
> use this
> .pac-container {
> z-index: 10000 !important;
> }

This worked like a charm, thanks! 😄🙌

my particular solution on Angular 9+ was :

```
::ng-deep .pac-container {
  z-index: 99999999 !important;
}
```

**Comment by HON9LIN** [comment]
I am experiencing the same issue and really not sure why altering `z-index` can be a solution. Actually, it does not work correctly on my side.

The reason we are having this issue is that the `pac-container` does not have `position: relative` parent.
![image](https://user-images.githubusercontent.com/59565606/119634443-6ef6e200-be1b-11eb-8a5c-1b2dea4e579b.png)
Is there any other solution for this issue? Thank you.

My project environment:
```
...
"@angular/core": "~12.0.0",
"@angular/material": "^12.0.0",
"ngx-google-places-autocomplete": "^2.0.5",
...
```

My Angular environment:
```
Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 7.14.0
OS: linux x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@nguniversal/builders           12.0.0
@nguniversal/express-engine     12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by eliyas5044** [comment]
I had to add `position: fixed` in the global **style.scss** file for **Angular 11**
```css
.pac-container {
  z-index: 99999999 !important;
  position: fixed !important;
}
```

**Comment by NiajM** [comment]
> use this .pac-container { z-index: 10000 !important; }

dropdown is not sticks with the input, it's not about z-index.
