### ISSUE TITLE
google is not defined

### ISSUE THREAD

**Issue by apoorva-chikara** [skynet2/ngx-google-places-autocomplete#5]
![issue](https://user-images.githubusercontent.com/34681515/36658292-d51b8bc0-1af5-11e8-8d22-0771309257f1.PNG)

I have followed the same steps given in readme, I have noted that the package installed from npm doesn't have GooglePlaceDirective. However, I have added one but still facing same issues. Can anyone help me how to resolve this issue?

**Comment by apoorva-chikara** [comment]
I am able to resolve it.

There were some path conflicts, which i resolved.

Thanks

**Comment by cdiaz** [comment]
@apoorva-chikara, How did you solve it?
I have the following problem:
`Cannot find name 'GooglePlaceDirective'.`
