### ISSUE TITLE
How we can bind latlang to narrow our search.

### ISSUE THREAD

**Issue by prashantparihar63** [skynet2/ngx-google-places-autocomplete#50]
Hi,

Auto complete is working fine but there is no exapmle so we can set lat and lang to get more appropriate places result. I have spent around 20hrs on it but not found any solution.

My email id is prashants4@chetu.com

Thanks in advance.

**Comment by skynet2** [comment]
According to docs, google allows restricting search based on countries only https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries
