### ISSUE TITLE
Add the restriction for the particular country

### ISSUE THREAD

**Issue by VivekaLogu** [skynet2/ngx-google-places-autocomplete#55]
In which file we have to add the options to restrict the particular country on angular 8

**Comment by sbelaustegui** [comment]
@VivekaLogu you have to pass it throw HTML tag. something like this:

`<input ngx-google-places-autocomplete **[options]="autocompleteOptions"** type="text"
                            aria-label="Number"
                            placeholder="Dónde?"
                            matInput
                            (onAddressChange)="handleAddressChange($event)" />`

Then in the .ts you declared the object like this:
`autocompleteOptions = {
    componentRestrictions: { country: 'AR' }
  };`
