### ISSUE TITLE
Google is not defined

### ISSUE THREAD

**Issue by aormontero** [skynet2/ngx-google-places-autocomplete#6]
I am trying to implement the component but some issue appears , ERROR ReferenceError,  google is not defined in this line. 

<input ngx-google-places-autocomplete [options]='options' #placesRef="ngx-places" (onAddressChange)="handleAddressChange($event)"/>

**Comment by skynet2** [comment]
hi @aormontero ,

Please ensure that you added 
`    <script src="https://maps.googleapis.com/maps/api/js?key=<Your API KEY>&libraries=places&sensor=false&language=en"></script>
`

in the head section of your html code.
