### ISSUE TITLE
(onAddressChange) not fired with Angular10

### ISSUE THREAD

**Issue by MatDepInfo** [skynet2/ngx-google-places-autocomplete#62]
I used ngx-google-places-autocomplete without troubles. But since I updated to Angular10, the event (onAddressChange) is not fired any more. Any solution ?

**Comment by Jonas-Merforth** [comment]
I just ran into the same problem, for me adding `'place_id'` into the fields parameter of the options works as a workaround. Not a soltution to the problem but better than always having to request all items.

**Comment by Jonas-Merforth** [comment]
It is because of this line btw: 
https://github.com/skynet2/ngx-google-places-autocomplete/blob/707ddd9bfc58c5e3135e2d5dd3cba6e647cfc7a5/src/ngx-google-places-autocomplete.directive.ts#L94

**Comment by skynet2** [comment]
Fixed in 2.0.5, please update. (#47 )
