### ISSUE TITLE
How to set text on init?

### ISSUE THREAD

**Issue by warrendodsworth** [skynet2/ngx-google-places-autocomplete#7]
Tried this
this.placesRef.place = new Address();
this.placesRef.place.formatted_address = 'TEST PLACE';

Not sure how the this.place  = this.autocomplete.getPlace() decides that formatted_address goes in the text box

**Comment by skynet2** [comment]
hi @warrendodsworth ,

According to an official doc (https://developers.google.com/maps/documentation/javascript/places-autocomplete#placeholder_text), you can specify placeholder on your input field.

So you can try smth like : 
`<input ngx-google-places-autocomplete [options]='options' #placesRef="ngx-places" (onAddressChange)="handleAddressChange($event)" placeholder="my awesome text"/>
`

Thanks,
Stas

**Comment by warrendodsworth** [comment]
Already doing that and it works as expected. 
When a record needs to be edited I need to put the existing address into the box, I'm looking for a way to do this.
Thank you.

**Comment by skynet2** [comment]
Hi @warrendodsworth , 
According to google doc, there is no built-in functionality to specify the output format. 
The only solution (is more like a hack) is https://stackoverflow.com/a/20148342

Thanks,
Stas
