### ISSUE TITLE
How to work with multiple autocomplete boxes in same component.

### ISSUE THREAD

**Issue by ChakralaKartheek** [skynet2/ngx-google-places-autocomplete#8]
Hi,

I have a real-time scenario, I need to use multiple autocomplete boxes (mostly dynamic) in one component like, in that case, how can I get which autoComplete box address has changed,

**HTML Code** 
`  <input  class="form-control" placeholder="Starting Point" ngx-google-places-autocomplete #places="ngx-places" (onAddressChange)="handleAddressChange($event)" />`

**Component Code**
` public handleAddressChange(address: Address) {
   console.log(address);
  }`

Help me how to deal with this.

**Comment by skynet2** [comment]
Hell @ChakralaKartheek ,

Sorry for long response, for some reason missed your ticket.
There are two ways to implement this, the easy one (without dynamic) : 
`<input class="form-control" placeholder="Starting Point" ngx-google-places-autocomplete #places="ngx-places" (onAddressChange)="handleAddressChange($event,1)" />
<input class="form-control" placeholder="Starting Point" ngx-google-places-autocomplete #places="ngx-places" (onAddressChange)="handleAddressChange($event,2)" />` 
.....
Or the dynamic one
`<input class="form-control" placeholder="Starting Point" ngx-google-places-autocomplete #places="ngx-places" (onAddressChange)="handleAddressChange($event,this)" />` `
Using this way, you will need to change your function 
`public handleAddressChange(address: Address, ref: GooglePlaceDirective) { console.log(address); console.log(ref); }`
Under ref there will be a reference to google places directive with reference to a specific html el in it.

Thanks,
Stas
