### ISSUE TITLE
disabled chrome autofill

### ISSUE THREAD

**Issue by robert-king** [skynet2/ngx-google-places-autocomplete#9]
<img width="867" alt="screen shot 2018-06-19 at 4 04 40 pm" src="https://user-images.githubusercontent.com/793016/41576293-ab5253b2-73da-11e8-90fb-14a70733198c.png">

from the photo you can see autofill goes over the top which makes the user experience not very nice. I wasn't able to find a fix for this.

**Comment by skynet2** [comment]
Hi @robert-king , 

Please try this solution 

<input ... autocomplete="off">

Ref https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

Thanks,
Stas

**Comment by robert-king** [comment]
@skynet2  thanks but that doesn't work for chrome autofill. (I already have autocomplete="off").

[See stackoverflow](https://stackoverflow.com/questions/29931712/chrome-autofill-covers-autocomplete-for-google-maps-api-v3)

Here is a fix someone made for angularJS:

```
(function(){
  'use strict'; 
  angular.module('app.directive')
    .directive('stopAutofill', stopAutofillDirective);

  function stopAutofillDirective() {
      return {
        restrict: 'A',
        link: function (scope, element) {
            var observerHack = new MutationObserver(function () {
                observerHack.disconnect();
                element.attr("autocomplete", "new-password");
            });

            observerHack.observe(element[0], {
                attributes: true,
                attributeFilter: ['autocomplete']
            });
        }
      };
    };
})();
```

**Comment by skynet2** [comment]
hello @robert-king ,

Did you try this solution ? https://stackoverflow.com/a/50907563

Thanks,
Stas

**Comment by saicharanbollampally** [comment]
Hi @skynet2 and @robert-king ,

I am facing same issue, let me know if you found any solution.

I tried above links but didn't work.

**Comment by sterichards** [comment]
@skynet2 It doesn't matter what value we set `autocomplete` to in the HTML template

The `ngx-google-places-autocomplete` directive overrides it and sets `autocomplete="off"` which is not good because of the Chrome bug which ignores `autocomplete="off"`

We *need* to be able to force `autocomplete` to a value of the *developers choice*
